### ISSUE TITLE
Angular 11 Support

### ISSUE THREAD

**Issue by elesueur** [remackgeek/elements-zone-strategy#10]
I'm filing this issue to help us determine whether there are changes needed to support Angular 11, or whether we can just bump the peer dependency to include Angular 11.

**Comment by remackgeek** [comment]
Sorry about the slow response -- I didn't have my notifications set correctly.
You don't need elements-zone-strategy with Angular 11 (actually, since 10.1) -- the fix has been incorporated in @angular/elements. see [here](https://github.com/angular/angular/pull/37814).

I've updated the readme and will push it out to npm when CircleCI maintenance is done. You can see the updated readme now on [github](https://github.com/remackgeek/elements-zone-strategy)

**Comment by remackgeek** [comment]
Readme is updated in both github and npm.
